# Generated by Django 6.0.4 on 2026-04-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "ادمین سیستم"),
                    ("Mananger", "مدیر سیستم"),
                    ("MEMBER", "عضو عادی"),
                ],
                default="MEMBER",
                max_length=10,
                verbose_name="نقش کاربری",
            ),
        ),
    ]
