# Generated by Django 6.0.4 on 2026-05-03 09:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("goal", models.CharField(max_length=255)),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (1, "1 Week (1w)"),
                            (2, "2 Weeks (2w)"),
                            (3, "3 Weeks (3w)"),
                        ],
                        default=2,
                    ),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="task",
            old_name="Project",
            new_name="project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.AddField(
            model_name="task",
            name="attachment",
            field=models.ImageField(blank=True, null=True, upload_to="project/"),
        ),
        migrations.AddField(
            model_name="task",
            name="issu_type",
            field=models.CharField(
                choices=[("T", "Task"), ("S", "Story"), ("B", "Bug")],
                default="T",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="tasks.sprint",
            ),
        ),
    ]
