# Generated by Django 6.0.4 on 2026-05-04 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_sprint_rename_project_task_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
