# Generated by Django 6.0.4 on 2026-05-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_task_reporter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="issu_type",
            new_name="issue_type",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="title",
            new_name="summary",
        ),
    ]
